SwarmSH AGI System Dashboard
============================
System: {{ system.name }} v{{ system.version }}
Environment: {{ environment | upper }}
Deployment: {{ deployment.region }} ({{ deployment.cluster }})

System Health: {{ system.health }}/100
{% if system.health > 90 %}
🟢 EXCELLENT - System performing optimally
{% elif system.health > 75 %}
🟡 GOOD - System stable with minor optimization opportunities  
{% else %}
🔴 ATTENTION - System requires immediate attention
{% endif %}

Current Status ({{ live.timestamp }})
=====================================
Uptime: {{ live.uptime_seconds }} seconds
Memory Usage: {{ live.memory_usage }}%
CPU Usage: {{ live.cpu_usage }}%
Network Connections: {{ live.network_connections }}

AGI Agent Pool
==============
{% for agent in agents %}
Agent: {{ agent.id }}
  Role: {{ agent.role | upper }}
  Status: {{ agent.status | upper }}
  Capacity: {{ agent.capacity }}/100
  Specialization: {{ agent.specialization }}
  
{% endfor %}

Performance Metrics  
==================
Total Operations: {{ metrics.total_operations | default:"0" }}
Success Rate: {{ metrics.success_rate }}%
Average Response Time: {{ metrics.avg_response_time }}ms
Context Compositions: {{ metrics.context_compositions }}
Schema Validations: {{ metrics.schema_validations }}
Security Scans: {{ metrics.security_scans }}

Real-time Load
==============
Current Load: {{ realtime.current_load }}%
Active Renders: {{ realtime.active_renders }}
Queue Depth: {{ realtime.queue_depth }}

Computed Intelligence
====================
Failure Count: {{ computed.failure_count }}
Efficiency Score: {{ computed.efficiency_score }}
Performance Tier: {{ computed.performance_tier | upper }}
Analysis Time: {{ computed.computed_at }}

System Summary
==============
{% if computed.performance_tier == "excellent" %}
✅ AGI system is operating at peak efficiency
{% elif computed.performance_tier == "good" %}
⚠️  AGI system is stable with optimization potential
{% else %}
❌ AGI system requires performance tuning
{% endif %}

Generated by SwarmSH AGI Template Engine v3.0.0
Context Sources: {{ _context_source_count | default:"multiple" }}
Schema Validated: ✅
Security Scanned: ✅
Optimized: ✅
