# Prometheus Configuration for Ollama Pro Testing

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ollama-pro-test'

rule_files:
  # Add alerting rules here if needed

scrape_configs:
  # Scrape metrics from OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 5s
    metrics_path: /metrics
    
  # Scrape collector internal metrics
  - job_name: 'otel-collector-internal'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 10s
    
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    
  # Scrape any additional ollama-pro metrics
  - job_name: 'ollama-pro-metrics'
    static_configs:
      - targets: ['host.docker.internal:8890']  # If ollama-pro exposes metrics
    scrape_interval: 5s
    scrape_timeout: 5s